[tuntox] Add daemon package (tuntoxd)

diff --git a/tuntox/spec.template b/tuntox/spec.template
--- a/tuntox/spec.template
+++ b/tuntox/spec.template
@@ -3,6 +3,10 @@
 %global _libdir     %{_prefix}/%{_project}/lib
 %global _includedir %{_prefix}/%{_project}/include
 
+%if 0%{?centos} == 7 || 0%{?fedora} >= 15 || 0%{?suse_version} >= 1210
+%define with_systemd 1
+%endif
+
 Name:           %PACKAGE%
 Version:        %VERSION%
 Release:        1
@@ -21,6 +25,28 @@ low-latency access to distant machines behind a NAT you can't control or with
 a dynamic IP address.
 
 
+%package -n     tuntoxd
+Summary:        tuntox daemon
+Group:          Productivity/Networking/Talk/Servers
+Requires:       %{name} = %{version}-%{release}
+%if 0%{?suse_version}
+Requires(pre):  pwdutils
+%else
+Requires(pre):  shadow-utils
+%endif
+
+%if 0%{?with_systemd}
+BuildRequires:  systemd
+%if 0%{?suse_version}
+BuildRequires:  systemd-rpm-macros
+%endif
+%{?systemd_requires}
+%endif
+
+%description -n tuntoxd
+This package contains tuntox daemon
+
+
 %prep
 %setup -q -n %{name}
 
@@ -36,6 +62,100 @@ make PREFIX=%{_prefix} USER_CFLAGS="%{USER_CFLAGS}" USER_LDFLAGS="%{USER_LDFLAGS
 %install
 install -D -m755 %{name} %{buildroot}%{_bindir}/%{name}
 
+ln -s %{_bindir}/%{name} %{buildroot}%{_bindir}/tuntoxd
+
+install -D -m 0644 debian/tuntoxd.default %{buildroot}%{_sysconfdir}/sysconfig/tuntoxd
+
+%if 0%{?suse_version}
+install -d -m 0755 %{buildroot}%{_sbindir}
+%endif
+
+%if 0%{?with_systemd}
+install -D -m 0644 tuntoxd.service  %{buildroot}%{_unitdir}/tuntoxd.service
+install -D -m 0644 tuntoxd.tmpfiles %{buildroot}%{_tmpfilesdir}/tuntoxd.conf
+%if 0%{?suse_version}
+ln -s -f %{_sbindir}/service %{buildroot}%{_sbindir}/rctuntoxd
+%endif
+%else
+%if 0%{?centos} == 6
+install -D -m 0755 tuntoxd.centos.sh %{buildroot}%{_sysconfdir}/init.d/tuntoxd
+%else
+install -D -m 0755 debian/tuntoxd.init %{buildroot}%{_sysconfdir}/init.d/tuntoxd
+%endif
+%if 0%{?suse_version}
+ln -s -f %{_sysconfdir}/init.d/tuntoxd %{buildroot}%{_sbindir}/rctuntoxd
+%endif
+%endif
+
+
+%pre -n tuntoxd
+if ! getent passwd tuntoxd > /dev/null 2>&1 ; then
+    useradd -c "Account to run tuntox daemon" -r -d /var/lib/tuntoxd -m -s /sbin/nologin -U tuntoxd
+    chmod 700 /var/lib/tuntoxd
+    chown -R tuntoxd:tuntoxd /var/lib/tuntoxd
+fi
+%if 0%{?with_systemd}
+%if 0%{?suse_version}
+%service_add_pre tuntoxd.service
+%endif
+%endif
+
+
+%post -n tuntoxd
+%if 0%{?with_systemd}
+%if 0%{?suse_version}
+%service_add_post tuntoxd.service
+%else
+%systemd_post tuntoxd.service
+%endif
+systemd-tmpfiles --create tuntoxd.conf
+%else
+%if 0%{?suse_version}
+%fillup_and_insserv tuntoxd
+%else
+/sbin/chkconfig --add tuntoxd
+%endif
+%endif
+
+
+%preun -n tuntoxd
+%if 0%{?with_systemd}
+%if 0%{?suse_version}
+%service_del_preun tuntoxd.service
+%else
+%systemd_preun tuntoxd.service
+%endif
+%else
+%if 0%{?suse_version}
+%stop_on_removal tuntoxd
+%else
+if [ $1 -eq 0 ]; then
+    /sbin/service tuntoxd stop > /dev/null 2>&1 || :
+    /sbin/chkconfig --del tuntoxd
+fi
+%endif
+%endif
+
+
+%postun -n tuntoxd
+%if 0%{?with_systemd}
+%if 0%{?suse_version}
+%service_del_postun tuntoxd.service
+%else
+%systemd_postun_with_restart tuntoxd.service
+%endif
+%else
+%if 0%{?suse_version}
+%restart_on_update tuntoxd
+%insserv_cleanup
+%else
+if [ $1 -ge 1 ]; then
+    /sbin/service tuntoxd status  > /dev/null 2>&1 || exit 0
+    /sbin/service tuntoxd restart > /dev/null 2>&1 || echo "Restart failed, please check system log"
+fi
+%endif
+%endif
+
 
 %files
 %defattr(-,root,root,-)
@@ -45,7 +165,35 @@ install -D -m755 %{name} %{buildroot}%{_bindir}/%{name}
 %dir %{_bindir}
 %endif
 
-%{_bindir}/*
+%{_bindir}/tuntox
+
+
+%files -n tuntoxd
+%defattr(-,root,root,-)
+
+%if 0%{?suse_version}
+%if 0%{?with_systemd}
+%dir %{_unitdir}
+%dir %{_tmpfilesdir}
+%else
+%dir %{_sysconfdir}/init.d
+%endif
+%endif
+
+%{_bindir}/tuntoxd
+
+%config(noreplace) %{_sysconfdir}/sysconfig/tuntoxd
+
+%if 0%{?with_systemd}
+%{_unitdir}/tuntoxd.service
+%{_tmpfilesdir}/tuntoxd.conf
+%else
+%{_sysconfdir}/init.d/tuntoxd
+%endif
+
+%if 0%{?suse_version}
+%{_sbindir}/rctuntoxd
+%endif
 
 
 %changelog
